---
version: 2
jobs:
  test: &test
    docker:
      - image: oclif/nsis:0.0.2-9.11.1
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v6-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v6-yarn-{{checksum ".circleci/config.yml"}}
      - run: .circleci/greenkeeper
      - run: .circleci/loadgpg
      - run: yarn add -D nyc@11 @oclif/nyc-config@1
      - run: ./node_modules/.bin/tsc
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run: |
          $NYC yarn test
          curl -s https://codecov.io/bash | bash
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - run: .circleci/loadgpg
      - restore_cache: *restore_cache
      - run: yarn global add @oclif/semantic-release@3 semantic-release@15
      - run: yarn --frozen-lockfile
      - run: ./bin/run pack
      - run: ./bin/run pack:deb
      - run: ./bin/run pack:win
      - run: ./bin/run publish
      - run: |
          export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
          semantic-release -e @oclif/semantic-release
      - run: yarn add -D nyc@11 @oclif/nyc-config@1
      - save_cache:
          key: v6-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - ~/cli/tmp/cache
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/dev-cli":
    jobs:
      - test
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - test
